[[positions]]
id = "LFRR_AI_CTR"
prefixes = ["LFRR"]
frequency = "132.025"
facility_type = "CTR"
default_call_sources = ["LFRR_AI"]

[[positions]]
id = "LFRR_AU_CTR"
prefixes = ["LFRR"]
frequency = "126.265"
facility_type = "CTR"
default_call_sources = ["LFRR_AU", "LFRR_AI"]

[[positions]]
id = "LFRR_A_CTR"
prefixes = ["LFRR"]
frequency = "124.675"
facility_type = "CTR"
default_call_sources = ["LFRR_A", "LFRR_AI", "LFRR_AU"]

[[positions]]
id = "LFRR_CTR"
prefixes = ["LFRR"]
frequency = "125.500"
facility_type = "CTR"
default_call_sources = [
  "LFRR_AI",
  "LFRR_A",
  "LFRR_AU",
  "LFRR_GI",
  "LFRR_G",
  "LFRR_GU",
  "LFRR_J",
  "LFRR_KI",
  "LFRR_KS",
  "LFRR_KU",
  "LFRR_MI",
  "LFRR_MS",
  "LFRR_MU",
  "LFRR_NF",
  "LFRR_NI",
  "LFRR_NS",
  "LFRR_NU",
  "LFRR_QI",
  "LFRR_QS",
  "LFRR_QE",
  "LFRR_VI",
  "LFRR_VS",
  "LFRR_VU",
  "LFRR_WI",
  "LFRR_WS",
  "LFRR_XI",
  "LFRR_XS",
  "LFRR_XU",
  "LFRR_ZI",
  "LFRR_ZS",
  "LFRR_ZU",
]

[[positions]]
id = "LFRR_E_CTR"
prefixes = ["LFRR"]
frequency = "136.000"
facility_type = "CTR"
default_call_sources = [
  "LFRR_MI",
  "LFRR_MS",
  "LFRR_MU",
  "LFRR_QI",
  "LFRR_QS",
  "LFRR_QE",
  "LFRR_XI",
  "LFRR_XS",
  "LFRR_XU",
  "LFRR_ZI",
  "LFRR_ZS",
  "LFRR_ZU",
]

[[positions]]
id = "LFRR_GI_CTR"
prefixes = ["LFRR"]
frequency = "132.240"
facility_type = "CTR"
default_call_sources = ["LFRR_GI"]

[[positions]]
id = "LFRR_GU_CTR"
prefixes = ["LFRR"]
frequency = "131.280"
facility_type = "CTR"
default_call_sources = ["LFRR_GU"]

[[positions]]
id = "LFRR_G_CTR"
prefixes = ["LFRR"]
frequency = "124.065"
facility_type = "CTR"
default_call_sources = ["LFRR_G", "LFRR_GI", "LFRR_GU"]

[[positions]]
id = "LFRR_J_CTR"
prefixes = ["LFRR"]
frequency = "127.385"
facility_type = "CTR"
default_call_sources = ["LFRR_J"]

[[positions]]
id = "LFRR_K_CTR"
prefixes = ["LFRR"]
frequency = "119.825"
facility_type = "CTR"
default_call_sources = ["LFRR_KI", "LFRR_KS", "LFRR_KU"]

[[positions]]
id = "LFRR_M_CTR"
prefixes = ["LFRR"]
frequency = "135.965"
facility_type = "CTR"
default_call_sources = ["LFRR_MI", "LFRR_MS", "LFRR_MU"]

[[positions]]
id = "LFRR_N_CTR"
prefixes = ["LFRR"]
frequency = "118.030"
facility_type = "CTR"
default_call_sources = ["LFRR_NF", "LFRR_NI", "LFRR_NS", "LFRR_NU"]

[[positions]]
id = "LFRR_Q_CTR"
prefixes = ["LFRR"]
frequency = "132.185"
facility_type = "CTR"
default_call_sources = ["LFRR_QI", "LFRR_QS", "LFRR_QE"]

[[positions]]
id = "LFRR_S_CTR"
prefixes = ["LFRR"]
frequency = "133.550"
facility_type = "CTR"
default_call_sources = [
  "LFRR_AI",
  "LFRR_A",
  "LFRR_AU",
  "LFRR_GI",
  "LFRR_G",
  "LFRR_GU",
  "LFRR_NF",
  "LFRR_NI",
  "LFRR_NS",
  "LFRR_NU",
]

[[positions]]
id = "LFRR_UE_CTR"
prefixes = ["LFRR"]
frequency = "130.235"
facility_type = "CTR"
default_call_sources = [
  "LFRR_MI",
  "LFRR_MU",
  "LFRR_QI",
  "LFRR_QE",
  "LFRR_XI",
  "LFRR_XU",
  "LFRR_ZI",
  "LFRR_ZU",
]

[[positions]]
id = "LFRR_US_CTR"
prefixes = ["LFRR"]
frequency = "131.280"
facility_type = "CTR"
default_call_sources = [
  "LFRR_AI",
  "LFRR_AU",
  "LFRR_GI",
  "LFRR_GU",
  "LFRR_NI",
  "LFRR_NU",
]

[[positions]]
id = "LFRR_VK_CTR"
prefixes = ["LFRR"]
frequency = "124.775"
facility_type = "CTR"
default_call_sources = ["LFRR_KI", "LFRR_KU", "LFRR_VI", "LFRR_VU"]

[[positions]]
id = "LFRR_V_CTR"
prefixes = ["LFRR"]
frequency = "118.865"
facility_type = "CTR"
default_call_sources = ["LFRR_VI", "LFRR_VS", "LFRR_VU"]

[[positions]]
id = "LFRR_WI_CTR"
prefixes = ["LFRR"]
frequency = "135.260"
facility_type = "CTR"
default_call_sources = ["LFRR_WI"]

[[positions]]
id = "LFRR_WU_CTR"
prefixes = ["LFRR"]
frequency = "133.615"
facility_type = "CTR"
default_call_sources = ["LFRR_WI"]

[[positions]]
id = "LFRR_W_CTR"
prefixes = ["LFRR"]
frequency = "129.505"
facility_type = "CTR"
default_call_sources = [
  "LFRR_WS",
  "LFRR_WI",
  "LFRR_J",
  "LFRR_KI",
  "LFRR_KS",
  "LFRR_KU",
  "LFRR_VI",
  "LFRR_VS",
  "LFRR_VU",
]

[[positions]]
id = "LFRR_X_CTR"
prefixes = ["LFRR"]
frequency = "125.965"
facility_type = "CTR"
default_call_sources = ["LFRR_XI", "LFRR_XS", "LFRR_XU"]

[[positions]]
id = "LFRR_Z_CTR"
prefixes = ["LFRR"]
frequency = "134.335"
facility_type = "CTR"
default_call_sources = ["LFRR_ZI", "LFRR_ZS", "LFRR_ZU"]

[[positions]]
id = "LFRB_APP"
prefixes = ["LFRB"]
frequency = "125.860"
facility_type = "APP"
default_call_sources = ["LFRB_APP", "LFRB_IN_APP", "LFRB_IS_APP", "LFRH_APP"]

[[positions]]
id = "LFRB_IN_APP"
prefixes = ["LFRB"]
frequency = "119.575"
facility_type = "APP"
default_call_sources = ["LFRB_IN_APP", "LFRB_IS_APP"]

[[positions]]
id = "LFRB_IS_APP"
prefixes = ["LFRB"]
frequency = "135.830"
facility_type = "APP"
default_call_sources = ["LFRB_IS_APP"]

[[positions]]
id = "LFRN_DD_APP"
prefixes = ["LFRN"]
frequency = "126.950"
facility_type = "APP"
default_call_sources = ["LFRN_DD_APP"]

[[positions]]
id = "LFRN_JC_APP"
prefixes = ["LFRN"]
frequency = "134.200"
facility_type = "APP"
default_call_sources = ["LFRN_JC_APP"]

[[positions]]
id = "LFRN_JD_APP"
prefixes = ["LFRN"]
frequency = "120.350"
facility_type = "APP"
default_call_sources = ["LFRN_JD_APP"]

[[positions]]
id = "LFRN_RN_APP"
prefixes = ["LFRN"]
frequency = "134.000"
facility_type = "APP"
default_call_sources = [
  "LFRN_RN_APP",
  "LFRN_DD_APP",
  "LFRN_JC_APP",
  "LFRN_JD_APP",
]

[[positions]]
id = "LFRS_IE_APP"
prefixes = ["LFRS"]
frequency = "130.275"
facility_type = "APP"
default_call_sources = ["LFRS_IE_APP", "LFRS_IW_APP"]

[[positions]]
id = "LFRS_IW_APP"
prefixes = ["LFRS"]
frequency = "119.400"
facility_type = "APP"
default_call_sources = ["LFRS_IW_APP"]

[[positions]]
id = "LFRS_LU_APP"
prefixes = ["LFRS"]
frequency = "119.535"
facility_type = "APP"
default_call_sources = ["LFRS_LU_APP"]

[[positions]]
id = "LFRS_NA_APP"
prefixes = ["LFRS"]
frequency = "120.125"
facility_type = "APP"
default_call_sources = ["LFRS_NA_APP"]

[[positions]]
id = "LFRS_NB_APP"
prefixes = ["LFRS"]
frequency = "124.250"
facility_type = "APP"
default_call_sources = ["LFRS_NB_APP", "LFRS_NA_APP"]

[[positions]]
id = "LFRS_RS_APP"
prefixes = ["LFRS"]
frequency = "124.430"
facility_type = "APP"
default_call_sources = [
  "LFRS_RS_APP",
  "LFRS_LU_APP",
  "LFRS_NB_APP",
  "LFRS_NA_APP",
  "LFRS_IE_APP",
  "LFRS_IW_APP",
]

[[positions]]
id = "LFEA_I_TWR"
prefixes = ["LFEA"]
frequency = "118.755"
facility_type = "TWR"
default_call_sources = ["LFEA_I_TWR"]

[[positions]]
id = "LFEQ_I_TWR"
prefixes = ["LFEQ"]
frequency = "119.605"
facility_type = "TWR"
default_call_sources = ["LFEQ_I_TWR"]

[[positions]]
id = "LFEY_I_TWR"
prefixes = ["LFEY"]
frequency = "118.905"
facility_type = "TWR"
default_call_sources = ["LFEY_I_TWR"]

[[positions]]
id = "LFJR_I_TWR"
prefixes = ["LFJR"]
frequency = "124.705"
facility_type = "TWR"
default_call_sources = ["LFJR_I_TWR"]

[[positions]]
id = "LFOH_I_TWR"
prefixes = ["LFOH"]
frequency = "135.205"
facility_type = "TWR"
default_call_sources = ["LFOH_I_TWR"]

[[positions]]
id = "LFOU_I_TWR"
prefixes = ["LFOU"]
frequency = "120.405"
facility_type = "TWR"
default_call_sources = ["LFOU_I_TWR"]

[[positions]]
id = "LFOV_I_TWR"
prefixes = ["LFOV"]
frequency = "120.805"
facility_type = "TWR"
default_call_sources = ["LFOV_I_TWR"]

[[positions]]
id = "LFRB_TWR"
prefixes = ["LFRB"]
frequency = "120.105"
facility_type = "TWR"
default_call_sources = ["LFRB_TWR"]

[[positions]]
id = "LFRC_I_TWR"
prefixes = ["LFRC"]
frequency = "119.630"
facility_type = "TWR"
default_call_sources = ["LFRC_I_TWR"]

[[positions]]
id = "LFRD_TWR"
prefixes = ["LFRD"]
frequency = "120.155"
facility_type = "TWR"
default_call_sources = ["LFRD_TWR"]

[[positions]]
id = "LFRE_I_TWR"
prefixes = ["LFRE"]
frequency = "121.405"
facility_type = "TWR"
default_call_sources = ["LFRE_I_TWR"]

[[positions]]
id = "LFRG_TWR"
prefixes = ["LFRG"]
frequency = "118.305"
facility_type = "TWR"
default_call_sources = ["LFRG_TWR"]

[[positions]]
id = "LFRH_TWR"
prefixes = ["LFRH"]
frequency = "119.700"
facility_type = "TWR"
default_call_sources = ["LFRH_TWR", "LFRH_GND"]

[[positions]]
id = "LFRI_I_TWR"
prefixes = ["LFRI"]
frequency = "119.905"
facility_type = "TWR"
default_call_sources = ["LFRI_I_TWR"]

[[positions]]
id = "LFRK_TWR"
prefixes = ["LFRK"]
frequency = "134.530"
facility_type = "TWR"
default_call_sources = ["LFRK_TWR", "LFRK_GND"]

[[positions]]
id = "LFRM_I_TWR"
prefixes = ["LFRM"]
frequency = "199.998"
facility_type = "TWR"
default_call_sources = ["LFRM_I_TWR"]

[[positions]]
id = "LFRN_TWR"
prefixes = ["LFRN"]
frequency = "120.505"
facility_type = "TWR"
default_call_sources = ["LFRN_TWR", "LFRN_GND"]

[[positions]]
id = "LFRO_I_TWR"
prefixes = ["LFRO"]
frequency = "118.405"
facility_type = "TWR"
default_call_sources = ["LFRO_I_TWR"]

[[positions]]
id = "LFRQ_TWR"
prefixes = ["LFRQ"]
frequency = "118.625"
facility_type = "TWR"
default_call_sources = ["LFRQ_TWR"]

[[positions]]
id = "LFRS_TWR"
prefixes = ["LFRS"]
frequency = "118.650"
facility_type = "TWR"
default_call_sources = ["LFRS_TWR", "LFRS_GND"]

[[positions]]
id = "LFRU_I_TWR"
prefixes = ["LFRU"]
frequency = "118.505"
facility_type = "TWR"
default_call_sources = ["LFRU_I_TWR"]

[[positions]]
id = "LFRV_I_TWR"
prefixes = ["LFRV"]
frequency = "122.605"
facility_type = "TWR"
default_call_sources = ["LFRV_I_TWR"]

[[positions]]
id = "LFRZ_TWR"
prefixes = ["LFRZ"]
frequency = "118.950"
facility_type = "TWR"
default_call_sources = ["LFRZ_TWR"]

[[positions]]
id = "LFRH_GND"
prefixes = ["LFRH"]
frequency = "119.700"
facility_type = "GND"
default_call_sources = ["LFRH_GND"]

[[positions]]
id = "LFRK_GND"
prefixes = ["LFRK"]
frequency = "121.790"
facility_type = "GND"
default_call_sources = ["LFRK_GND"]

[[positions]]
id = "LFRN_GND"
prefixes = ["LFRN"]
frequency = "121.730"
facility_type = "GND"
default_call_sources = ["LFRN_GND"]

[[positions]]
id = "LFRJ_APP"
prefixes = ["LFRJ"]
frequency = "122.400"
facility_type = "APP"
default_call_sources = ["LFRJ_APP"]

[[positions]]
id = "LFRJ_TWR"
prefixes = ["LFRJ"]
frequency = "119.200"
facility_type = "TWR"
default_call_sources = ["LFRJ_TWR"]

[[positions]]
id = "LFRL_APP"
prefixes = ["LFRL"]
frequency = "120.600"
facility_type = "APP"
default_call_sources = ["LFRL_APP"]

[[positions]]
id = "LFRL_TWR"
prefixes = ["LFRL"]
frequency = "123.200"
facility_type = "TWR"
default_call_sources = ["LFRL_TWR", "LFRL_GND"]

[[positions]]
id = "LFRL_GND"
prefixes = ["LFRL"]
frequency = "121.900"
facility_type = "GND"
default_call_sources = ["LFRL_GND"]

[[positions]]
id = "LFRS_GND"
prefixes = ["LFRS"]
frequency = "121.655"
facility_type = "GND"
default_call_sources = ["LFRS_GND"]
