[[stations]]
id = "LFRR_AI"
controlled_by = [
  "LFRR_AI_CTR",
  "LFRR_AU_CTR",
  "LFRR_A_CTR",
  "LFRR_US_CTR",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRR_A"
controlled_by = ["LFRR_A_CTR", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_AU"
controlled_by = [
  "LFRR_AU_CTR",
  "LFRR_A_CTR",
  "LFRR_US_CTR",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRR_GI"
controlled_by = [
  "LFRR_GI_CTR",
  "LFRR_G_CTR",
  "LFRR_US_CTR",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRR_G"
controlled_by = ["LFRR_G_CTR", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_GU"
controlled_by = [
  "LFRR_GU_CTR",
  "LFRR_G_CTR",
  "LFRR_US_CTR",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRR_J"
controlled_by = ["LFRR_J_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_KI"
controlled_by = ["LFRR_K_CTR", "LFRR_VK_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_KS"
controlled_by = ["LFRR_K_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_KU"
controlled_by = ["LFRR_K_CTR", "LFRR_VK_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_MI"
controlled_by = ["LFRR_M_CTR", "LFRR_UE_CTR", "LFRR_E_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_MS"
controlled_by = ["LFRR_M_CTR", "LFRR_E_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_MU"
controlled_by = ["LFRR_M_CTR", "LFRR_UE_CTR", "LFRR_E_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_NF"
controlled_by = ["LFRR_N_CTR", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_NI"
controlled_by = ["LFRR_N_CTR", "LFRR_US_CTR", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_NS"
controlled_by = ["LFRR_N_CTR", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_NU"
controlled_by = ["LFRR_N_CTR", "LFRR_US_CTR", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_QI"
controlled_by = [
  "LFRR_Q_CTR",
  "LFRR_UE_CTR",
  "LFRR_E_CTR",
  "LFRR_CTR",
  "PAR_CTR",
]

[[stations]]
id = "LFRR_QS"
controlled_by = ["LFRR_Q_CTR", "LFRR_E_CTR", "LFRR_CTR", "PAR_CTR"]

[[stations]]
id = "LFRR_QE"
controlled_by = [
  "LFRR_Q_CTR",
  "LFRR_UE_CTR",
  "LFRR_E_CTR",
  "LFRR_CTR",
  "PAR_CTR",
]

[[stations]]
id = "LFRR_VI"
controlled_by = ["LFRR_V_CTR", "LFRR_VK_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_VS"
controlled_by = ["LFRR_V_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_VU"
controlled_by = ["LFRR_V_CTR", "LFRR_VK_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_WI"
controlled_by = ["LFRR_WU_CTR", "LFRR_WI_CTR", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_WS"
controlled_by = ["LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRR_XI"
controlled_by = [
  "LFRR_X_CTR",
  "LFRR_UE_CTR",
  "LFRR_E_CTR",
  "LFRR_CTR",
  "PAR_CTR",
]

[[stations]]
id = "LFRR_XS"
controlled_by = ["LFRR_X_CTR", "LFRR_E_CTR", "LFRR_CTR", "PAR_CTR"]

[[stations]]
id = "LFRR_XU"
controlled_by = [
  "LFRR_X_CTR",
  "LFRR_UE_CTR",
  "LFRR_E_CTR",
  "LFRR_CTR",
  "PAR_CTR",
]

[[stations]]
id = "LFRR_ZI"
controlled_by = [
  "LFRR_Z_CTR",
  "LFRR_UE_CTR",
  "LFRR_E_CTR",
  "LFRR_CTR",
  "PAR_CTR",
]

[[stations]]
id = "LFRR_ZS"
controlled_by = ["LFRR_Z_CTR", "LFRR_E_CTR", "LFRR_CTR", "PAR_CTR"]

[[stations]]
id = "LFRR_ZU"
controlled_by = [
  "LFRR_Z_CTR",
  "LFRR_UE_CTR",
  "LFRR_E_CTR",
  "LFRR_CTR",
  "PAR_CTR",
]

[[stations]]
id = "LFRB_APP"
controlled_by = ["LFRB_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRB_IN_APP"
controlled_by = ["LFRB_IN_APP", "LFRB_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRB_IS_APP"
controlled_by = [
  "LFRB_IS_APP",
  "LFRB_IN_APP",
  "LFRB_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRJ_APP"
controlled_by = ["LFRJ_APP", "LFFM_CTR"]

[[stations]]
id = "LFRL_APP"
controlled_by = ["LFRL_APP", "LFFM_CTR"]

[[stations]]
id = "LFRN_RN_APP"
controlled_by = ["LFRN_RN_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRN_DD_APP"
controlled_by = ["LFRN_DD_APP", "LFRN_RN_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRN_JD_APP"
controlled_by = ["LFRN_JD_APP", "LFRN_RN_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRN_JC_APP"
controlled_by = [
  "LFRN_JC_APP",
  "LFRN_JD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRS_LU_APP"
controlled_by = ["LFRS_LU_APP", "LFRS_RS_APP", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRS_NA_APP"
controlled_by = ["LFRS_NA_APP", "LFRS_RS_APP", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRS_NB_APP"
controlled_by = [
  "LFRS_NB_APP",
  "LFRS_NA_APP",
  "LFRS_RS_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRS_RS_APP"
controlled_by = ["LFRS_RS_APP", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRS_IE_APP"
controlled_by = ["LFRS_IE_APP", "LFRS_RS_APP", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRS_IW_APP"
controlled_by = [
  "LFRS_IW_APP",
  "LFRS_IE_APP",
  "LFRS_RS_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFEA_I_TWR"
controlled_by = [
  "LFEA_I_TWR",
  "LFRS_IW_APP",
  "LFRS_IE_APP",
  "LFRS_NB_APP",
  "LFRS_NA_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFEQ_I_TWR"
controlled_by = [
  "LFEQ_I_TWR",
  "LFRS_IW_APP",
  "LFRS_IE_APP",
  "LFRS_NB_APP",
  "LFRS_NA_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFEY_I_TWR"
controlled_by = [
  "LFEY_I_TWR",
  "LFRS_IW_APP",
  "LFRS_IE_APP",
  "LFRS_NB_APP",
  "LFRS_NA_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFJR_I_TWR"
controlled_by = [
  "LFJR_I_TWR",
  "LFRS_IE_APP",
  "LFRS_NB_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFOH_I_TWR"
controlled_by = [
  "LFOH_I_TWR",
  "LFRN_JD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFOU_I_TWR"
controlled_by = ["LFOU_I_TWR"]

[[stations]]
id = "LFOV_I_TWR"
controlled_by = ["LFOV_I_TWR", "LFRN_RN_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRB_TWR"
controlled_by = ["LFRB_TWR", "LFRB_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRC_I_TWR"
controlled_by = [
  "LFRC_I_TWR",
  "LFRN_JC_APP",
  "LFRN_JD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRD_TWR"
controlled_by = [
  "LFRD_TWR",
  "LFRN_DD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRE_I_TWR"
controlled_by = [
  "LFRE_I_TWR",
  "LFRS_IW_APP",
  "LFRS_IE_APP",
  "LFRS_NB_APP",
  "LFRS_NA_APP",
  "LFRS_RS_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRG_TWR"
controlled_by = [
  "LFRG_TWR",
  "LFRN_JD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRH_APP"
controlled_by = ["LFRH_APP", "LFRB_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRH_TWR"
parent_id = "LFRH_APP"
controlled_by = ["LFRH_TWR"]

[[stations]]
id = "LFRI_I_TWR"
controlled_by = [
  "LFRI_I_TWR",
  "LFRS_NB_APP",
  "LFRS_RS_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRJ_TWR"
controlled_by = ["LFRJ_TWR", "LFRJ_APP", "LFFM_CTR"]

[[stations]]
id = "LFRK_TWR"
controlled_by = [
  "LFRK_TWR",
  "LFRN_JD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRL_TWR"
controlled_by = ["LFRL_TWR", "LFRL_APP", "LFFM_CTR"]

[[stations]]
id = "LFRM_I_TWR"
controlled_by = [
  "LFRM_I_TWR",
  "LFRS_NB_APP",
  "LFRS_RS_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRN_TWR"
controlled_by = ["LFRN_TWR", "LFRN_RN_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRO_I_TWR"
controlled_by = ["LFRO_I_TWR", "LFRB_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRQ_TWR"
controlled_by = ["LFRQ_TWR", "LFRB_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRS_TWR"
controlled_by = [
  "LFRS_TWR",
  "LFRS_NB_APP",
  "LFRS_RS_APP",
  "LFRR_S_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRU_I_TWR"
controlled_by = [
  "LFRU_I_TWR",
  "LFRN_DD_APP",
  "LFRN_RN_APP",
  "LFRR_W_CTR",
  "LFRR_CTR",
]

[[stations]]
id = "LFRV_I_TWR"
controlled_by = ["LFRV_I_TWR", "LFRN_RN_APP", "LFRR_W_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRZ_TWR"
controlled_by = ["LFRZ_TWR", "LFRS_RS_APP", "LFRR_S_CTR", "LFRR_CTR"]

[[stations]]
id = "LFRH_GND"
parent_id = "LFRH_TWR"
controlled_by = ["LFRH_GND"]

[[stations]]
id = "LFRK_GND"
parent_id = "LFRK_TWR"
controlled_by = ["LFRK_GND"]

[[stations]]
id = "LFRL_GND"
parent_id = "LFRL_TWR"
controlled_by = ["LFRL_GND"]

[[stations]]
id = "LFRN_GND"
parent_id = "LFRN_TWR"
controlled_by = ["LFRN_GND"]

[[stations]]
id = "LFRS_GND"
parent_id = "LFRS_TWR"
controlled_by = ["LFRS_GND"]
