[[positions]]
id = "SAEF_FSS"
prefixes = ["SAEF"]
frequency = "133.950"
facility_type = "FSS"

[[positions]]
id = "BAIRES_CTR"
prefixes = ["BAIRES"]
frequency = "125.900"
facility_type = "CTR"

[[positions]]
id = "SACF_CTR"
prefixes = ["SACF"]
frequency = "128.800"
facility_type = "CTR"

[[positions]]
id = "SACF_N_CTR"
prefixes = ["SACFN"]
frequency = "125.100"
facility_type = "CTR"

[[positions]]
id = "SACF_S_CTR"
prefixes = ["SACFS"]
frequency = "126.500"
facility_type = "CTR"

[[positions]]
id = "SAEF_CTR"
prefixes = ["SAEF"]
frequency = "134.500"
facility_type = "CTR"

[[positions]]
id = "SAEF_N_CTR"
prefixes = ["SAEFN"]
frequency = "135.500"
facility_type = "CTR"

[[positions]]
id = "SAEF_S_CTR"
prefixes = ["SAEFS"]
frequency = "125.200"
facility_type = "CTR"

[[positions]]
id = "SAMF_CTR"
prefixes = ["SAMF"]
frequency = "126.600"
facility_type = "CTR"

[[positions]]
id = "SARR_CTR"
prefixes = ["SARR"]
frequency = "124.300"
facility_type = "CTR"

[[positions]]
id = "SAVF_CTR"
prefixes = ["SAVF"]
frequency = "126.750"
facility_type = "CTR"

[[positions]]
id = "SAVF_N_CTR"
prefixes = ["SAVFN"]
frequency = "125.500"
facility_type = "CTR"

[[positions]]
id = "SAVF_S_CTR"
prefixes = ["SAVFS"]
frequency = "125.700"
facility_type = "CTR"

[[positions]]
id = "SAAC_APP"
prefixes = ["SAAC"]
frequency = "118.300"
facility_type = "APP"

[[positions]]
id = "SAAG_APP"
prefixes = ["SAAG"]
frequency = "118.400"
facility_type = "APP"

[[positions]]
id = "SAAP_APP"
prefixes = ["SAAP"]
frequency = "119.600"
facility_type = "APP"

[[positions]]
id = "SAAR_APP"
prefixes = ["SAAR"]
frequency = "118.700"
facility_type = "APP"

[[positions]]
id = "SACO_APP"
prefixes = ["SACO"]
frequency = "119.100"
facility_type = "APP"

[[positions]]
id = "SAME_APP"
prefixes = ["SAME"]
frequency = "124.200"
facility_type = "APP"

[[positions]]
id = "SAMM_APP"
prefixes = ["SAMM"]
frequency = "118.250"
facility_type = "APP"

[[positions]]
id = "SAMR_APP"
prefixes = ["SAMR"]
frequency = "118.100"
facility_type = "APP"

[[positions]]
id = "SANC_APP"
prefixes = ["SANC"]
frequency = "118.150"
facility_type = "APP"

[[positions]]
id = "SANE_APP"
prefixes = ["SANE"]
frequency = "118.700"
facility_type = "APP"

[[positions]]
id = "SANL_APP"
prefixes = ["SANL"]
frequency = "118.450"
facility_type = "APP"

[[positions]]
id = "SANT_APP"
prefixes = ["SANT"]
frequency = "123.850"
facility_type = "APP"

[[positions]]
id = "SANU_APP"
prefixes = ["SANU"]
frequency = "119.350"
facility_type = "APP"

[[positions]]
id = "SAOC_APP"
prefixes = ["SAOC"]
frequency = "118.750"
facility_type = "APP"

[[positions]]
id = "SAOR_APP"
prefixes = ["SAOR"]
frequency = "119.300"
facility_type = "APP"

[[positions]]
id = "SAOS_APP"
prefixes = ["SAOS"]
frequency = "119.950"
facility_type = "APP"

[[positions]]
id = "SAOU_APP"
prefixes = ["SAOU"]
frequency = "118.400"
facility_type = "APP"

[[positions]]
id = "SARE_APP"
prefixes = ["SARE"]
frequency = "119.400"
facility_type = "APP"

[[positions]]
id = "SARL_APP"
prefixes = ["SARL"]
frequency = "120.300"
facility_type = "APP"

[[positions]]
id = "SARP_APP"
prefixes = ["SARP"]
frequency = "120.100"
facility_type = "APP"

[[positions]]
id = "SASA_APP"
prefixes = ["SASA"]
frequency = "124.600"
facility_type = "APP"

[[positions]]
id = "SATR_APP"
prefixes = ["SATR"]
frequency = "119.000"
facility_type = "APP"

[[positions]]
id = "SAVC_APP"
prefixes = ["SAVC"]
frequency = "124.300"
facility_type = "APP"

[[positions]]
id = "SAVE_APP"
prefixes = ["SAVE"]
frequency = "118.800"
facility_type = "APP"

[[positions]]
id = "SAVT_APP"
prefixes = ["SAVT"]
frequency = "118.700"
facility_type = "APP"

[[positions]]
id = "SAVV_APP"
prefixes = ["SAVV"]
frequency = "118.300"
facility_type = "APP"

[[positions]]
id = "SAWB_APP"
prefixes = ["SAWB"]
frequency = "118.100"
facility_type = "APP"

[[positions]]
id = "SAWC_APP"
prefixes = ["SAWC"]
frequency = "119.950"
facility_type = "APP"

[[positions]]
id = "SAWE_APP"
prefixes = ["SAWE"]
frequency = "118.300"
facility_type = "APP"

[[positions]]
id = "SAWG_APP"
prefixes = ["SAWG"]
frequency = "124.700"
facility_type = "APP"

[[positions]]
id = "SAWH_APP"
prefixes = ["SAWH"]
frequency = "118.100"
facility_type = "APP"

[[positions]]
id = "SAZB_APP"
prefixes = ["SAZB"]
frequency = "124.800"
facility_type = "APP"

[[positions]]
id = "SAZM_APP"
prefixes = ["SAZM"]
frequency = "118.750"
facility_type = "APP"

[[positions]]
id = "SAZN_APP"
prefixes = ["SAZN"]
frequency = "119.800"
facility_type = "APP"

[[positions]]
id = "SAZR_APP"
prefixes = ["SAZR"]
frequency = "118.300"
facility_type = "APP"

[[positions]]
id = "SAZS_APP"
prefixes = ["SAZS"]
frequency = "119.100"
facility_type = "APP"

[[positions]]
id = "SAZT_APP"
prefixes = ["SAZT"]
frequency = "120.900"
facility_type = "APP"

[[positions]]
id = "SAZY_APP"
prefixes = ["SAZY"]
frequency = "119.600"
facility_type = "APP"

[[positions]]
id = "SAAI_TWR"
prefixes = ["SAAI"]
frequency = "130.800"
facility_type = "TWR"

[[positions]]
id = "SAAV_TWR"
prefixes = ["SAAV"]
frequency = "118.950"
facility_type = "TWR"

[[positions]]
id = "SABE_TWR"
prefixes = ["SABE"]
frequency = "118.850"
facility_type = "TWR"

[[positions]]
id = "SACE_TWR"
prefixes = ["SACE"]
frequency = "120.600"
facility_type = "TWR"

[[positions]]
id = "SACO_TWR"
prefixes = ["SACO"]
frequency = "118.300"
facility_type = "TWR"

[[positions]]
id = "SADF_TWR"
prefixes = ["SADF"]
frequency = "119.000"
facility_type = "TWR"

[[positions]]
id = "SADJ_TWR"
prefixes = ["SADJ"]
frequency = "119.700"
facility_type = "TWR"

[[positions]]
id = "SADM_TWR"
prefixes = ["SADM"]
frequency = "118.500"
facility_type = "TWR"

[[positions]]
id = "SADP_TWR"
prefixes = ["SADP"]
frequency = "120.300"
facility_type = "TWR"

[[positions]]
id = "SAEZ_TWR"
prefixes = ["SAEZ"]
frequency = "118.600"
facility_type = "TWR"

[[positions]]
id = "SAME_TWR"
prefixes = ["SAME"]
frequency = "119.900"
facility_type = "TWR"

[[positions]]
id = "SANR_TWR"
prefixes = ["SANR"]
frequency = "119.850"
facility_type = "TWR"

[[positions]]
id = "SANT_TWR"
prefixes = ["SANT"]
frequency = "119.500"
facility_type = "TWR"

[[positions]]
id = "SARC_TWR"
prefixes = ["SARC"]
frequency = "118.300"
facility_type = "TWR"

[[positions]]
id = "SARE_TWR"
prefixes = ["SARE"]
frequency = "118.700"
facility_type = "TWR"

[[positions]]
id = "SARF_TWR"
prefixes = ["SARF"]
frequency = "119.100"
facility_type = "TWR"

[[positions]]
id = "SARI_TWR"
prefixes = ["SARI"]
frequency = "120.700"
facility_type = "TWR"

[[positions]]
id = "SASA_TWR"
prefixes = ["SASA"]
frequency = "128.850"
facility_type = "TWR"

[[positions]]
id = "SASJ_TWR"
prefixes = ["SASJ"]
frequency = "118.700"
facility_type = "TWR"

[[positions]]
id = "SATG_TWR"
prefixes = ["SATG"]
frequency = "118.100"
facility_type = "TWR"

[[positions]]
id = "SAVC_TWR"
prefixes = ["SAVC"]
frequency = "119.900"
facility_type = "TWR"

[[positions]]
id = "SAVY_TWR"
prefixes = ["SAVY"]
frequency = "119.500"
facility_type = "TWR"

[[positions]]
id = "SAWG_TWR"
prefixes = ["SAWG"]
frequency = "119.400"
facility_type = "TWR"

[[positions]]
id = "SAZB_TWR"
prefixes = ["SAZB"]
frequency = "119.150"
facility_type = "TWR"

[[positions]]
id = "SAAR_GND"
prefixes = ["SAAR"]
frequency = "121.850"
facility_type = "GND"

[[positions]]
id = "SABE_GND"
prefixes = ["SABE"]
frequency = "121.900"
facility_type = "GND"

[[positions]]
id = "SACO_GND"
prefixes = ["SACO"]
frequency = "121.750"
facility_type = "GND"

[[positions]]
id = "SADF_GND"
prefixes = ["SADF"]
frequency = "121.850"
facility_type = "GND"

[[positions]]
id = "SADM_GND"
prefixes = ["SADM"]
frequency = "121.800"
facility_type = "GND"

[[positions]]
id = "SADP_GND"
prefixes = ["SADP"]
frequency = "121.950"
facility_type = "GND"

[[positions]]
id = "SAEZ_GND"
prefixes = ["SAEZ"]
frequency = "121.750"
facility_type = "GND"

[[positions]]
id = "SAME_GND"
prefixes = ["SAME"]
frequency = "121.950"
facility_type = "GND"

[[positions]]
id = "SANT_GND"
prefixes = ["SANT"]
frequency = "121.750"
facility_type = "GND"

[[positions]]
id = "SARE_GND"
prefixes = ["SARE"]
frequency = "121.950"
facility_type = "GND"

[[positions]]
id = "SAZM_GND"
prefixes = ["SAZM"]
frequency = "121.700"
facility_type = "GND"

[[positions]]
id = "SAZN_GND"
prefixes = ["SAZN"]
frequency = "121.800"
facility_type = "GND"

[[positions]]
id = "SAZS_GND"
prefixes = ["SAZS"]
frequency = "121.800"
facility_type = "GND"

[[positions]]
id = "SABE_DEL"
prefixes = ["SABE"]
frequency = "129.300"
facility_type = "DEL"

[[positions]]
id = "SADF_DEL"
prefixes = ["SADF"]
frequency = "129.500"
facility_type = "DEL"

[[positions]]
id = "SAEZ_DEL"
prefixes = ["SAEZ"]
frequency = "127.100"
facility_type = "DEL"
