name: CI • Dataset

on:
  workflow_call:

permissions: {}

jobs:
  schema:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install check-jsonschema
        run: pipx install check-jsonschema

      - name: Validate positions
        run: |
          shopt -s nullglob
          files=(dataset/*/positions.json dataset/*/positions.toml)
          if [ ${#files[@]} -gt 0 ]; then
            check-jsonschema --schemafile docs/schemas/positions.schema.json "${files[@]}"
          fi

      - name: Validate stations
        run: |
          shopt -s nullglob
          files=(dataset/*/stations.json dataset/*/stations.toml)
          if [ ${#files[@]} -gt 0 ]; then
            check-jsonschema --schemafile docs/schemas/stations.schema.json "${files[@]}"
          fi

      - name: Validate profiles
        run: |
          shopt -s nullglob
          files=(dataset/*/profiles/*.json)
          if [ ${#files[@]} -gt 0 ]; then
            check-jsonschema --schemafile docs/schemas/profiles.schema.json "${files[@]}"
          fi

      - name: Summary
        run: echo "### ✅ Schema validation - positions, stations & profiles" >> $GITHUB_STEP_SUMMARY

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Cache cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "linux-x86_64"
          workspaces: "tools -> target"

      - name: Validate dataset
        run: cargo run --quiet --release --locked --bin vacs-data --manifest-path tools/Cargo.toml -- --log-format github validate dataset/

      - name: Summary
        run: echo "### ✅ Dataset validation - all files valid" >> $GITHUB_STEP_SUMMARY
